<?php

namespace app\controllers;

use app\models\TestModel;
use Yii;
use yii\debug\panels\EventPanel;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public $enableCsrfValidation=false;
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

//    public function beforeAction($action)
//    {
//        echo '<pre>';
//        var_dump("Controller before action");
//        echo '/<pre>';
//        return parent::beforeAction($action); // TODO: Change the autogenerated stub
//    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
//        echo '<pre>';
//        var_dump(Yii::$app->test);
//        echo '</pre>';
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {   $this->layout='login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionHello($message)
    {
        return $this->render('hello', [
            'msg' => $message]);
    }

    public function actionTest()
    {
        $test = new TestModel();
        $test->name = 'John';
        $test->surname = 'Doe';
        $test->email = 'john@example.com';
        $test->myAge = 30;

        foreach ($test as $attr => $value) {
            echo $test->getAttributeLabel($attr) . '=' . $value . '<br>';
        }
        if ($test->validate()) {
            echo 'OK';
        } else {
            echo '<pre>';
            var_dump($test->errors);
            echo 'Error';
            echo '</pre>';
        }
    }


    public function actionRequest()
    {
//        $get = Yii::$app->request->post("name",'Thecodeholic');
//        echo '<pre>';
//        var_dump($get);
//        echo '</pre>';
//        echo Yii::$app->request->hostInfo;
//        var_dump(Yii::$app->request->getBodyParams());
            $req=Yii::$app->request;
            echo '<pre>';
            var_dump($req->userIP);
            echo '</pre>';


     }
     //metode de request-http://localhost:8080/index.php?r=site%2Fresponse
        public function actionResponse(){

        $response=Yii::$app->response->format= Response::FORMAT_JSON;
//        $response->statusCode=200;
//       $response->content='Hello from daniel';

//            Yii::$app->response->data= [
//              "name"=>'Daniel',
//                "surname"=>"dada"
//            ];
//                return $this->redirect('about',301);
                    return Yii::$app->response->sendStreamAsFile("hello", 'test.txt');

        }

}
