<?php

namespace app\widgets;

use yii\base\Widget;

class ButtonWidget extends Widget

{
    public $text;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->text=ucfirst($this->text);//face prima litera mare din text
    }

    public function run()
    {
        parent::run();
        return '<button>' . $this->text . '</button>';
    }

}